SocialNetwork.WebUI/Controllers/SocialMediaAccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SocialNetwork.Business.Abstract;
using SocialNetwork.Entities;
using SocialNetwork.WebUI.EntityHelper;
using SocialNetwork.WebUI.Models;
using System;
using System.Linq;
using System.Security.Claims;

namespace SocialNetwork.WebUI.Controllers
{
    public class SocialMediaAccountController : Controller
    {

        ISocialMediaAccountService _socialMediaAccountService;
        IUserService _userService;
        IBaseHelper _baseHelper;

        public SocialMediaAccountController(ISocialMediaAccountService socialMediaAccountService, IUserService userService, IBaseHelper baseHelper)
        {
            _socialMediaAccountService = socialMediaAccountService;
            _userService = userService;
            _baseHelper = baseHelper;
        }

        public IActionResult Index()
        {
            var claimuser = Guid.Parse(User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.Sid).Value);
            var socialMediaAccounts = _socialMediaAccountService.GetAll().ToList().Where(x => x.UserId == claimuser).ToList();
            return View(socialMediaAccounts);

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Delete(Guid id)
        {
            return View(_socialMediaAccountService.GetById(id));
        }

        [HttpPost]
        public IActionResult Delete(SocialMediaAccount socialMediaAccount)
        {
            _socialMediaAccountService.Delete(socialMediaAccount);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(Guid id)
        {
            return View(_socialMediaAccountService.GetById(id));
        }

        [HttpPost]
        public IActionResult Update(SocialMediaAccount socialMediaAccount)
        {
            if (!ModelState.IsValid)
                return View(socialMediaAccount);

            _baseHelper.UpdateDefaultProperty(socialMediaAccount);
            _socialMediaAccountService.Update(socialMediaAccount);

            return RedirectToAction("Update");
        }
    }
}

SocialNetwork.WebUI/Views/SocialMediaAccount/Create.cshtml
@model SocialMediaAccount

@{
    ViewData["Title"] = " Hesap Ekle";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-2">
                    <div class="form-group">
                        <label asp-for="SocialMediaName"></label>
                        <select class="form-control" asp-for="SocialMediaName" id="SocialMedia">
                            <option value="Facebook">Facebook</option>
                            <option value="Twitter">Twitter</option>
                            <option value="İnstagram">İnstagram</option>
                            <option value="LinkedIn">LinkedIn</option>
                            <option value="Youtube">Youtube</option>
                        </select>
                        <span asp-validation-for="SocialMediaName"></span>
                    </div>
                    <button class="btn btn-primary" id="save">Kaydet</button>
                    <a class="btn btn-danger float-right" asp-action="Index">Geri Dön</a>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
    $("#save").click(function () {
        var socialmedia = $("#SocialMedia").val();
        switch (socialmedia) {
            case "LinkedIn":
                window.location.href = "https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=78iyhahi3hob5p&redirect_uri=https%3A%2F%2Flocalhost%3A44316%2FLinkedin%2FLinkedinToken&state=foobar&scope=r_liteprofile%20r_emailaddress%20w_member_social"
                break;
            case "Facebook":
                window.location.href = "https://www.facebook.com/v6.0/dialog/oauth?client_id=698031151184178&redirect_uri=https%3A%2F%2Flocalhost%3A44316%2FFacebook%2FFacebookToken&scope=ads_management%20pages_read_engagement%20pages_manage_posts"
                break;
            case "Twitter":
                break;
            case "İnstagram":
                break;
            case "Youtube":
                break;
            default:
                break;
        }
    })
</script>

SocialNetwork.WebUI/Views/SocialMediaAccount/Delete.cshtml
@model SocialMediaAccount

@{
    ViewData["Title"] = " Hesap Sil";
}

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-2">
                    <form asp-controller="SocialMediaAccount" asp-action="Delete" method="post">
                        <div class="form-group">
                            <label asp-for="SocialMediaName"></label>
                            <select class="form-control" asp-for="SocialMediaName" disabled>
                                <option value="Facebook">Facebook</option>
                                <option value="Twitter">Twitter</option>
                                <option value="İnstagram">İnstagram</option>
                                <option value="LinkedIn">LinkedIn</option>
                                <option value="Youtube">Youtube</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label asp-for="Username"></label>
                            <input asp-for="Username" class="form-control" disabled/>
                        </div>
                        <div class="form-group">
                            <label asp-for="Token"></label>
                            <input asp-for="Token" class="form-control" disabled/>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-danger">Sil</button>
                            <a class="btn btn-danger float-right" asp-action="Index">Geri Dön</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

SocialNetwork.WebUI/Views/SocialMediaAccount/Index.cshtml
@model List<SocialMediaAccount>

@{
    ViewData["Title"] = " Hesaplar";
}

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-2">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(model => model[0].CreateDate)</th>
                                <th>@Html.DisplayNameFor(model => model[0].SocialMediaName)</th>
                                <th>@Html.DisplayNameFor(model => model[0].Username)</th>
                                @*<th>@Html.DisplayNameFor(model => model[0].Token)</th>*@
                                <th>
                                    <a asp-action="Create" type="button" class="btn btn-success col-md-5">Ekle</a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var socialMedia in (List<SocialMediaAccount>)Model)
                            {
                                <tr>
                                    <td>@socialMedia.CreateDate.ToShortDateString()</td>
                                    <td>@socialMedia.SocialMediaName</td>
                                    <td>@socialMedia.Username</td>
                                    @*<td>@socialMedia.Token</td>*@
                                    <td>
                                        <a type="button" asp-action="Delete" asp-route-id="@socialMedia.Id" class="btn btn-danger col-md-5">Sil</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

SocialNetwork.WebUI/Views/SocialMediaAccount/Update.cshtml
@model SocialMediaAccount

@{
    ViewData["Title"] = " Hesap Düzenle";
}

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body table-responsive p-2">
                    <form asp-controller="SocialMediaAccount" asp-action="Update" method="post">
                        <div class="form-group">
                            <label asp-for="SocialMediaName"></label>
                            <select class="form-control" asp-for="SocialMediaName">
                                <option value="Facebook">Facebook</option>
                                <option value="Twitter">Twitter</option>
                                <option value="İnstagram">İnstagram</option>
                                <option value="LinkedIn">LinkedIn</option>
                                <option value="Youtube">Youtube</option>
                            </select>
                            <span asp-validation-for="SocialMediaName"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Username"></label>
                            <input asp-for="Username" class="form-control" />
                            <span asp-validation-for="Username"></span>
                        </div>
                        @*<div class="form-group">
                            <label asp-for="Token"></label>
                            <input asp-for="Token" class="form-control" />
                            <span asp-validation-for="Token"></span>
                        </div>*@
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Güncelle</button>
                            <a class="btn btn-danger float-right" asp-action="Index">Geri Dön</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>